### PR TITLE
Updated usage of removed methods of JacocoReport task

### PR DESCRIPTION
**Pull request by autonomousapps**
This is necessary to continue using this plugin with Gradle 6.

### CODE REVIEW

**Comment by autonomousapps** [comment]
Gradle 6.0 was officially released today. What's the likelihood of this getting merged and a new version of the library published?

**Comment by autonomousapps** [comment]
Thanks!

**Comment by neugartf** [comment]
We would also like to see a release of this. :)

**Comment by jangrewe** [comment]
seconded, @arturdm - please create a new release! :-)

**Comment by radzio** [comment]
@arturdm - any updates about release with this PR?

**Comment by autonomousapps** [comment]
I published a forked version of this plugin at https://plugins.gradle.org/plugin/com.hiya.jacoco-android.

**Comment by mochadwi** [comment]
> I published a forked version of this plugin at https://plugins.gradle.org/plugin/com.hiya.jacoco-android.

thanks a lot, will use your version from now then

**Comment by neugartf** [comment]
*Push* @arturdm

**Comment by SujataSwamy** [comment]
> I published a forked version of this plugin at https://plugins.gradle.org/plugin/com.hiya.jacoco-android.

        I am getting below error after using the forked version. Does anybody know about this error?

        java.lang.ExceptionInInitializerError
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:49)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1124)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1131)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6370)
        at android.app.ActivityThread.access$1300(ActivityThread.java:248)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1830)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7266)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
     Caused by: java.lang.RuntimeException: Failed to initialize JaCoCo.
        at org.jacoco.agent.rt.internal_43f5073.Offline.getRuntimeData(Offline.java:41)
        at org.jacoco.agent.rt.internal_43f5073.Offline.getProbes(Offline.java:60)
        at com.miairline.shared.application.AirFiApplication.$jacocoInit(Unknown Source:13)
        at com.miairline.shared.application.AirFiApplication.<clinit>(Unknown Source:0)
        at java.lang.Class.newInstance(Native Method) 
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50) 
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:49) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1124) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1131) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6370) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:248) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1830) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7266) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975) 
     Caused by: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:308)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
        at org.jacoco.agent.rt.internal_43f5073.output.FileOutput.openFile(FileOutput.java:68)
        at org.jacoco.agent.rt.internal_43f5073.output.FileOutput.startup(FileOutput.java:50)
        at org.jacoco.agent.rt.internal_43f5073.Agent.startup(Agent.java:129)
        at org.jacoco.agent.rt.internal_43f5073.Agent.getInstance(Agent.java:54)
        at org.jacoco.agent.rt.internal_43f5073.Offline.getRuntimeData(Offline.java:39)
        at org.jacoco.agent.rt.internal_43f5073.Offline.getProbes(Offline.java:60) 
        at com.miairline.shared.application.AirFiApplication.$jacocoInit(Unknown Source:13) 
        at com.miairline.shared.application.AirFiApplication.<clinit>(Unknown Source:0) 
        at java.lang.Class.newInstance(Native Method) 
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50) 
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:49) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1124) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1131) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6370) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:248) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1830) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7266) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Pull request merged**
