### PR TITLE
Adding parameter to pass a pattern to execute only specific tests

### PR DESCRIPTION
**Pull request by pedrofraca**
Not sure if this can be done using another parameter, but did a research and couldn't find anything. Please take a look. Thanks

### CODE REVIEW

**Comment by WarrenFaith** [comment]
You should adapt your code to the obvious code style (like spaces around the `=`)

**Comment by WarrenFaith** [comment]
Can you also provide a small sample how to configure your change?
Would be nice to enhance the documentation this way.

**Comment by pedrofraca** [comment]
Here is the sample configuration for this property, if not set all tests will be launched.

jacocoAndroidUnitTestReport {
    tests='com.company.tests.*'
}

It can be configured also from the command line using a sytem property.

**Comment by arturdm** [comment]
Hi @pedrofraca and sorry to have kept you waiting. I don't feel this is the right plugin to put this change into. This plugin is supposed to do one thing right which is to add missing reports tasks for unit tests in Android projects.

As for filtering tests you can use Android Gradle plugin DSL to configure test tasks like this:

```gradle
android {
  testOptions {
    unitTests.all {
      it.testNameIncludePattern = "*.SomeTest"
    }
  }
}
```

You can find more details on `testOptions` [here]( http://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.TestOptions.UnitTestOptions.html#com.android.build.gradle.internal.dsl.TestOptions.UnitTestOptions:all%28groovy.lang.Closure%29) and test filters [here](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/TestFilter.html).

Hope it helps.

**Comment by pedrofraca** [comment]
Thanks @arturdm, this is working perfectly.

**Pull request closed without merging**
